// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smart_parking_system.Models;

#nullable disable

namespace smart_parking_system.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250417041732_UpdateRegistrationPackage")]
    partial class UpdateRegistrationPackage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("smart_parking_system.Models.RegistrationCarMonthly", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensedPlate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar");

                    b.Property<int>("RegistrationPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.HasIndex("RegistrationPackageId");

                    b.ToTable("RegistrationCarMonthly");
                });

            modelBuilder.Entity("smart_parking_system.Models.RegistrationPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("RegistratioSnFees")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("RegistrationPackage");
                });

            modelBuilder.Entity("smart_parking_system.Models.RegistrationCarMonthly", b =>
                {
                    b.HasOne("smart_parking_system.Models.RegistrationPackage", "RegistrationPackage")
                        .WithMany("RegistrationCarMonthlies")
                        .HasForeignKey("RegistrationPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistrationPackage");
                });

            modelBuilder.Entity("smart_parking_system.Models.RegistrationPackage", b =>
                {
                    b.Navigation("RegistrationCarMonthlies");
                });
#pragma warning restore 612, 618
        }
    }
}
